# Generated by Django 3.1.7 on 2021-03-22 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_booking_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='capacity',
        ),
    ]
