# Generated by Django 3.1.7 on 2021-03-23 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_room_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('PHY', 'Physics'), ('IT', 'Information Technology'), ('CHEM', 'Chemistry'), ('EEE', 'Electronic')], max_length=5)),
                ('resource_name', models.CharField(max_length=122, null=True)),
                ('resource_id', models.CharField(max_length=122, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='resource_booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined')], default='Pending', max_length=12)),
                ('select_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.booking')),
                ('select_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.resource')),
            ],
        ),
    ]
