# Generated by Django 3.1.7 on 2021-03-16 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210316_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_link',
            name='student',
        ),
        migrations.AddField(
            model_name='student_link',
            name='email',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='student_link',
            name='roll_number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
