# Generated by Django 3.1.7 on 2021-03-16 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210316_1057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='section_id',
            new_name='section',
        ),
    ]
