# Generated by Django 3.1.7 on 2021-03-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210316_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='section_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
