# Generated by Django 3.1.7 on 2021-03-16 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_section_section_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='section_id',
        ),
    ]
